### ISSUE TITLE
MemoryAddressList

### ISSUE THREAD

**Issue by YouTheB** [Lazuplis-Mei/pvzclass#10]
MemoryAddressList怎么读？
是加法还是替换低位？
想要知道当前关卡是否已经选卡结束发现没有变化
我监听的是6A9EC0+768+15C+2C=6AA7B0，选卡结束没有变化……

**Comment by Lazuplis-Mei** [comment]
6A9EC0+768+15C+2C=6AA7B0是只写数据，不能根据此数值来确定的确选卡状态
但是你可以通过6A9EC0+7FC来判断当前关卡的状态，2是选卡，3是开始游戏

**Comment by Lazuplis-Mei** [comment]
也就是说，你将6A9EC0+768+15C+2C改为1，可以强制结束选卡状态，但这个值本身不会自己改变
同时你也可以判断6A9EC0+774是否为0来判断选卡是否结束

**Comment by YouTheB** [comment]
thanks,懂了

**Comment by YouTheB** [comment]
汉化第一版监听6A9EC0+7FC并没有什么用，还是0，但是我发现28CA44C是关卡状态（是汉化第一版的锅吗），主界面1，选卡2，进入游戏3，迷你游戏/小游戏/生存模式选择是7

**Comment by Lazuplis-Mei** [comment]
无关汉化第一版的事情，6A9EC0+7FC一定是关卡状态，除非是年度版

**Comment by Lazuplis-Mei** [comment]
何况28CA44C根本不是一个指针，你是不是有哪里搞错了
![Y33L95%%K6M$3BPQOWPLXS7](https://user-images.githubusercontent.com/50167216/77602010-4b9a8380-6f47-11ea-8e6f-82a631f3d45f.png)

**Comment by Lazuplis-Mei** [comment]
何况28CA44C根本不是一个指针，你是不是有哪里搞错了
还是说，我得写成[[6A9EC0]+7FC]才能消除歧义
