### ISSUE TITLE
关于逆向思路的咨询

### ISSUE THREAD

**Issue by dellbeat** [Lazuplis-Mei/pvzclass#100]
您好，之前在搜索1051版本内存数据的资料时找到了本仓库，里面有很多我会用到的信息，但目前没有找到部分场景，如过关后场景内的"NEXT LEVEL"按钮的基础信息（如句柄、宽度、高度等）。
由于我没有太多的逆向工程经验，想咨询一下您先前汇总的偏移信息是您自己使用逆向工程得到的吗；如果是的话，我想知道如何获得场景内的按钮信息，希望您可以给一个大致的思路，我会自己去尝试摸索，谢谢！

**Comment by Moon-404** [comment]
是逆向得来的，不过前人已经总结了很多经验，宝开也开源了游戏的开发框架，可以对照着看

**Comment by dellbeat** [comment]
好的了解了 我再去搜索一下看看 感谢！
