### ISSUE TITLE
关于僵尸状态(+28)以及运动状态(+60)的枚举值定义。

### ISSUE THREAD

**Issue by dnartz** [Lazuplis-Mei/pvzclass#19]
请问最近关于这两项的研究有什么进展吗？我现在正在分析这两个枚举值所对应的含义。

**Comment by Lazuplis-Mei** [comment]
我早就已经不干了，不再做任何有关pvz的事情

**Comment by 63enjoy** [comment]
+28 ：0为正常 1为消失 2为变黑 3为秒杀

**Comment by dnartz** [comment]
enum class zombie_status {
    walking = 0x0,
    dying = 0x1,
    dying_from_instant_kill = 0x2,
    dying_from_lawnmower = 0x3,
    bungee_target_drop = 0x4,
    bungee_body_drop = 0x5,
    bungee_idle_after_drop = 0x6,
    bungee_grab = 0x7,
    bungee_raise = 0x8,
    bungee_idle = 0xa,
    pole_valuting_running = 0xb,
    pole_valuting_jumpping = 0xc,
    pole_vaulting_walking = 0xd,
    rising_from_ground = 0xe,
    jackbox_walking = 0xf,
    jackbox_pop = 0x10,
    pogo_with_stick = 0x14,
    pogo_idle_before_target = 0x15,
    pogo_jump_across = 0x1b,
    newspaper_walking = 0x1d,
    newspaper_destoryed = 0x1e,
    newspaper_running = 0x1f,
    digger_dig = 0x20,
    digger_drill = 0x21,
    digger_lost_dig = 0x22,
    digger_landing = 0x23,
    digger_dizzy = 0x24,
    digger_walk_right = 0x25,
    digger_walk_left = 0x26,
    digger_idle = 0x27,
    dancing_moonwalk = 0x28,
    dancing_point = 0x29,
    dancing_wait_summoning = 0x2a,
    dancing_summoning = 0x2b,
    dancing_walking = 0x2c,
    dancing_armrise1 = 0x2d,
    dancing_armrise2 = 0x2e,
    dancing_armrise3 = 0x2f,
    dancing_armrise4 = 0x30,
    dancing_armrise5 = 0x31,
    backup_spawning = 0x32,
    dophin_walk_with_dophin = 0x33,
    dophin_jump_in_pool = 0x34,
    dophin_ride = 0x35,
    dophin_jump = 0x36,
    dophin_walk_in_pool = 0x37,
    dophin_walk_without_dophin = 0x38,
    snorkel_walking = 0x39,
    snorkel_jump_in_the_pool = 0x3a,
    snorkel_swim = 0x3b,
    snorkel_up_to_eat = 0x3c,
    snorkel_eat = 0x3d,
    snorkel_finied_eat = 0x3e,
    catapult_shoot = 0x43,
    catapult_idle = 0x44,
    balloon_flying = 0x49,
    balloon_falling = 0x4a,
    balloon_walking = 0x4b,
    imp_flying = 0x47,
    imp_landing = 0x48,
    gargantuar_throw = 0x45,
    gargantuar_smash = 0x46,
    ladder_walking = 0x4c,
    ladder_placing = 0x4d,
    yeti_escape = 0x5b,
};

enum class plant_status {
    idle = 0x0,
    wait = 0x1,
    work = 0x2,
    squash_look = 0x3,
    squash_jump_up = 0x4,
    squash_stop_in_the_air = 0x5,
    squash_jump_down = 0x6,
    squash_crushed = 0x7,
    grave_buster_land = 0x8,
    grave_buster_idle = 0x9,
    chomper_bite_begin = 0xA,
    chomper_bite_success = 0xB,
    chomper_bite_fail = 0xC,
    chomper_chew = 0xD,
    chomper_swallow = 0xE,
    potato_sprout_out = 0xF,
    potato_armed = 0x10,
    spike_attack = 0x12,
    scaredyshroom_scared = 0x14,
    scaredyshroom_scared_idle = 0x15,
    scaredyshroom_grow = 0x16,
    sunshroom_small = 0x17,
    sunshroom_grow = 0x18,
    sunshroom_big = 0x19,
    magnetshroom_working = 0x1A,
    magnetshroom_inactive_idle = 0x1B,
    cactus_short_idle = 0x1E,
    cactus_grow_tall = 0x1F,
    cactus_tall_idle = 0x20,
    cactus_get_short = 0x21,
    tangle_kelp_grab = 0x22,
    cob_cannon_unaramed_idle = 0x23,
    cob_cannon_charge = 0x24,
    cob_cannon_launch = 0x25,
    cob_cannon_aramed_idle = 0x26,
    kernelpult_launch_butter = 0x27,
    umbrella_leaf_block = 0x28,
    umbrella_leaf_shrink = 0x29,
    imitater_explode = 0x2A,
    flower_pot_placed = 0x2F,
    lily_pad_placed = 0x30
};

这是我找到的一些状态值

**Comment by theflysong** [comment]
建议把他们整理后添加到代码里发个pr
