### ISSUE TITLE
尝试了一下发现只有中文版可以用

### ISSUE THREAD

**Issue by Lengjunyi** [Lazuplis-Mei/pvzclass#22]
执行了范例代码，但是不知道为什么，英文版的无法更改阳光，而且PVZ实例的base_address为0。但是中文版没有这个问题。

**Comment by Lazuplis-Mei** [comment]
很简单，只是单纯没有对应的进程而已
因为英文原版的进程名字不对应，如果你指的是英文原版的话，会同时存在一个用于防破解的后台进程外壳PlantsVsZombies.exe，你需要用popcapgame1.exe的进程名才能找到游戏

**Comment by Lazuplis-Mei** [comment]
另外，我已经不干了，如果还有类似的问题，你可以尝试去问其他的使用者或者在最近几次提交中表现活跃的代码提供者，他们也会比你更了解的

**Comment by Lengjunyi** [comment]
> 很简单，只是单纯没有对应的进程而已
> 因为英文原版的进程名字不对应，如果你指的是英文原版的话，会同时存在一个用于防破解的后台进程外壳PlantsVsZombies.exe，你需要用popcapgame1.exe的进程名才能找到游戏

感谢，已经解决了，打扰您了

**Comment by Lazuplis-Mei** [comment]
你可以用通过pvz->GameVersion来确认当前的版本，虽然这相比常规的判断（来自于终极修改器中的PVZClass）来说更严格

**Comment by Lazuplis-Mei** [comment]
原则上只有V1_0_0_1051完全支持，V1_2_0_1065支持成员的访问不支持涉及汇编的调用，其他均为完全不支持
