### ISSUE TITLE
字符编码和类型转换问题

### ISSUE THREAD

**Issue by happyme531** [Lazuplis-Mei/pvzclass#23]
1.这个库的源码是GB2312编码，如果不用vs2019并且没有特别的设置的话就会蹦出成吨的语法错误，只要转换成utf-8就没问题了
我本来想直接用git submodule把库集成进项目里，但是由于这个问题放弃了

2.ProcessOpener.cpp中类型转换报错。eg.:
`LPCWSTR ProcessOpener::ProcessName = TEXT("PlantsVsZombies.exe");`
“初始化”: 无法从“const char [20]”转换为“LPCWSTR”
"const char *" 类型的值不能用于初始化 "LPCWSTR" 类型的实体
改成下面这样一切正常
`LPCWSTR ProcessOpener::ProcessName = TEXT((LPCWSTR)"PlantsVsZombies.exe");`

**Comment by Lazuplis-Mei** [comment]
关于这个无法从“const char [20]”转换为“LPCWSTR”实际上也是和你的项目设置有关系的
