### ISSUE TITLE
关于内存释放

### ISSUE THREAD

**Issue by Moon-404** [Lazuplis-Mei/pvzclass#34]
我发现程序的内存消耗随着时间线性增长，启用了堆分析发现是在使用了 `PVZ::GetAllZombies` 之类的函数时，程序会 `new PVZ::Zombie(i)` 。
在以下代码段运行结束后，这些内存似乎并不会释放：
``` C++
PVZ::Zombies* zombies[256];
pPVZ->GetAllZombies(zombies);
delete[] zombies;
```
请问我应该怎样正确地释放那些内存

**Comment by Moon-404** [comment]
刚刚尝试进行了以下修改，发现内存增长明显下降，不确定这种解决方式是否正确。如果您确认这种解决方式是正确的，我过段时间发个PR上来。
``` c++
int PVZ::GetAllPlants(Plant* plants[])
{
	int maxnum = Memory::ReadMemory<int>(BaseAddress + 0xB0);
	int j = 0;
	for (int i = 0; i < maxnum; i++)
	{
		if (!Memory::ReadMemory<byte>(Memory::ReadMemory<int>(BaseAddress + 0xAC) + 0x141 + 0x14C * i))
		{
			Plant* _t;
			_t = new PVZ::Plant(i);
			plants[j] = _t;
			delete _t;
			j++;
		}
	}
	return j;
}
```

**Comment by Lazuplis-Mei** [comment]
诸如Plant和Zombie的类型其实并不具备真正的内存存储结构，除了一个必要的BaseAddress以及DebugType（在调试时），其余的属性均不占用任何的内存空间，因此我没有为这些类型编写析构函数，你可以尝试这么做（尽管我不知道这具体是如何进行的），所以理论上一个Zombie对象只会占用8字节内存空间，这很大程度上导致我忽视了这一部分问题知道它们暴露。


你的修改事实上进行在了为数组的元素赋值的步骤上，因为对象是指针类型的，我想指针的数组在此方式下是没有影响的，除非在此处没有发生对象的引用指向，而是发生了一个隐含的复制行为，如果是后者，这个修改就是切实有效的，你可以确认此处delete _t的_t指针是否等同于你获取到plants中的对象指针

**Comment by Moon-404** [comment]
确实，单个Plant和Zombie对象占用很少，但还是需要合适的清理。
我刚刚把 GetAllPlants 和 GetAllZombies 的代码进行了更改，内存消耗大幅降低。
但是有一个问题，在我这样修改了僵尸的获取代码后，有时修改会不起作用（比如对全场共7个僵尸造成伤害，实际上只有6个僵尸受到了伤害），这让我现在有点头疼。
另外，Creater里的很多函数也并没有自动释放内存。
（所以我终于知道为什么之前的弹幕代码运行一段时间就崩了）

**Comment by Lazuplis-Mei** [comment]
这很有可能预示着delete _t的_t指针的确等同于你获取到plants中的对象指针，而不是一次复制行为，如果这样的话，delete[] plants应当可以成功的，也许你可以试着用for循环一个一个delete

**Comment by Lazuplis-Mei** [comment]
其实我觉得最重要的是，我在函数内部只能以这种方式编写，并不是我没有进行合适的清理，而是在函数内部无法这么做，否则就不能将对象传递出函数（以非new方式创建的对象在函数退出后自动销毁，new方式创建的对象本来的目的就是要在函数外部使用的，在函数内delete就没有意义了），鉴于C++的这个机制，此处这部分工作就是都应该在主调函数完成的，比如说Creater里的很多函数，不是不自动释放内存，是并不能释放内存，否则当函数调用结束后对象就会消失，这一点你应该比我更了解的，所以当你CreatePlant后，只能在你的主调函数里delete返回的plant

**Comment by ZhouZiHao-Moon** [comment]
我认为它是复制行为
1. delete[] plants 我之前试过，确实失败了
2. delete _t 确实可以极大减少内存消耗
至于为什么有时候修改会不起作用，我在 watch 窗口中确认了 GetAllZombies 获取到了正确的指针并且返回值也是正确的，所以我认为有可能是我实际修改的僵尸 0x6C 项的问题，我是通过将其改成 -2 使僵尸不前进，改成 0 使僵尸前进，刚刚发现有个别僵尸不会恢复前进，而通过调试工具再运行一次循环就恢复了，怪怪的。

Creater 后的对象确实应该在主调函数里 delete，这点我现在想明白了。

**Comment by Lazuplis-Mei** [comment]
我没有系统化的学习C++，我知道C++里有拷贝构造函数等的概念，现在想到复制行为实际上应该是在这里进行的，如果是这样的话，就真如我一开始所说的是一种复制行为了，而不是一个指针的引用传递行为

**Comment by Moon-404** [comment]
不过局部变量在函数退出时不是应该自动释放吗

**Comment by Lazuplis-Mei** [comment]
new出来的对象在函数退出后也不会释放，Plant plant(0);这样声明的对象在函数退出时是自动释放的，所以如果你想把值传递到函数外的话，应当使用new，我是这么认为的

**Comment by Lazuplis-Mei** [comment]
如果这样可以解决问题的话（我无法确认它，你知道的，我连pvz都没有）
```
int PVZ::GetAllPlants(Plant plants[])
{
	int maxnum = Memory::ReadMemory<int>(BaseAddress + 0xB0);
	int j = 0;
	for (int i = 0; i < maxnum; i++)
	{
		if (!Memory::ReadMemory<byte>(Memory::ReadMemory<int>(BaseAddress + 0xAC) + 0x141 + 0x14C * i))
		{
			Plant _t(i);
			plants[j] = _t;
			j++;
		}
	}
	return j;
}
```

**Comment by Moon-404** [comment]
数据类型似乎有点问题？

**Comment by Lazuplis-Mei** [comment]
是的我把Plant* plants[]改成Plant plants[]了，有什么问题吗

**Comment by Lazuplis-Mei** [comment]
那你还是用最开始的吧

**Comment by Lazuplis-Mei** [comment]
只能说抱歉我不能解决你的问题，因为我刚才写了一份等价的代码进行实验，结果表面在函数内部没有发生任何的对象复制行为，是同一个指针的引用传递，而在函数内delete确实会连同数组内的对象一起销毁(因为是同一个指针你知道的)，至少在我这边，我的结论是我的函数内只能按最初的写法，delete的工作应在外部完成

**Comment by Lazuplis-Mei** [comment]
总之我现在就只有一个建议，不要修改我的函数，试着在外部用for循环一个一个delete

**Comment by Moon-404** [comment]
那外部 delete 的正确方式是什么

```c++
PVZ::Zombies* zombies[256];
int num = pPVZ->GetAllZombies(zombies);
delete[] zombies;
for(int i = 0; i < num; i++) delete zombies[i];
```

使用第三行的方式还是第四行的方式呢？

**Comment by Lazuplis-Mei** [comment]
既然你很确定第三行不行的话，那就用第四行吧

**Comment by Moon-404** [comment]
似乎都不行……

**Comment by Lazuplis-Mei** [comment]
理论上，delete[]是和new[]成对使用的，但是
PVZ::Zombie* zombies[256];
根本就没有new，我查了一下，只有这么写
PVZ::Zombie* zombies = new PVZ::Zombie(256);
这样的才可以使用delete[]，但这里直接实例化256个对象，根本就不符合仅提供空间的本意，我不知道在什么地方出现了问题

**Comment by Moon-404** [comment]
另外，像第三行那样写会有警告：
warning C4154: 删除数组表达式；转换到提供的指针

**Comment by Moon-404** [comment]
这也是我疑惑的地方，没有 new 的 delete 似乎不合理。

**Comment by Lazuplis-Mei** [comment]
这些鬼问题就是我自从完成这个后就再也没有真正用过c++的主要原因了，其实吧，你在这里发issue基本等同于直接问我，也许你应该去询问一个精通c++的人

**Comment by Moon-404** [comment]
```C++
PVZ::Zombies* zombies[256];
int num = pPVZ->GetAllZombies(zombies);
for(int i = 0; i < num; i++) delete zombies[i];
```

这应当是正确的方法，我对C++还不是很懂

**Comment by theflysong** [comment]
应该要使用unique_ptr

**Comment by theflysong** [comment]
或许使用shared_ptr更好
