### ISSUE TITLE
关于虚拟点击

### ISSUE THREAD

**Issue by Moon-404** [Lazuplis-Mei/pvzclass#35]
```c++
void PVZ::Mouse::GameClick(int x, int y)
``` 

您好，我找到了这个函数，但它似乎并没有鼠标状态的参数？那它是以鼠标左键点击吗？如果想模拟鼠标中键和右键的点击应该使用什么方式？

**Comment by Lazuplis-Mei** [comment]
这个参数事实上在AsmFunctions.cpp的__asm__GameClick定义，但是我忘记它是具体参数了，因为我的资料早就删掉了
以及你总是可以使用WMClick来代替GameClick

**Comment by Lazuplis-Mei** [comment]
当然这个参数也可能是AsmFuntions.h第66行的这个0
#define GAMECLICK INVOKE_DWORD(0x539390,0)
如果你不介意修改并尝试的话

**Comment by Moon-404** [comment]
我修改了VMClick函数，增加了按键种类选择和按下时长，这表现得很好。
然而，还有一个小问题，这个X和Y的坐标似乎和系统的缩放挂钩，有什么比较好的解决方案吗？

**Comment by Lazuplis-Mei** [comment]
这个我不知道，不过我想你应该可以通过获取系统的缩放比例来计算出你想点击的位置，听起来是有点笨拙，但这至少是个办法，事实上我的修改器就是这样处理的
