### ISSUE TITLE
如何获取PVZ的运行状态

### ISSUE THREAD

**Issue by Moon-404** [Lazuplis-Mei/pvzclass#36]
PVZ在崩溃后（弹出Fatal Error对话框）的时候 PVZGameState 并不会改成一个特殊的值，那么有什么办法可以获取到PVZ的运行状态吗（比如未启动、正常运行、Fatal Error崩溃等）

**Comment by theflysong** [comment]
暂无方法

**Comment by 63enjoy** [comment]
6a9ec0 340 一字节，为true时代表pvz已经崩溃
