### ISSUE TITLE
关卡事件无法准确地监听

### ISSUE THREAD

**Issue by Yumesaka13** [Lazuplis-Mei/pvzclass#39]
除了LevelLeave、LevelWave这两个关卡监听事件有效，**LevelOpen、LevelStart**事件无法准确监听，只有**第一次打开关卡**，或**退出关卡重新进入**才可以监听到，在关卡内**重启开始**，**无法监听**到，请问如何修复？

**Comment by theflysong** [comment]
在关卡内**重启开始**的确**做不到**
因为LevelOpen与LevelStart事件是以pvz->BaseAddress变为**非NULL值**后触发的
目前没有发现在关卡内**重启开始**会导致什么值变化
如果您**有余力**的话可以尝试去寻找相应的值
毕竟PvzClass是位于PVZ之外的
只能靠其内部状态的一些改变来判断触发了什么

**Comment by Yumesaka13** [comment]
> 
> 
> 在关卡内**重启开始**的确**做不到**
> 因为LevelOpen与LevelStart事件是以pvz->BaseAddress变为**非NULL值**后触发的
> 目前没有发现在关卡内**重启开始**会导致什么值变化
> 如果您**有余力**的话可以尝试去寻找相应的值
> 毕竟PvzClass是位于PVZ之外的
> 只能靠其内部状态的一些改变来判断触发了什么

那么能不能在每次在关卡外打开关卡后吧address的值记录到另一个变量中，然后循环检测006a9ec0+768的值，如果6a9ec0+768的值和刚才存的变量不相等，address=6a9ec0+768的值，且判断为LevelOpen

**Comment by theflysong** [comment]
也许可以
你可以尝试一下
如果可以
你可以试着交一个pr

**Comment by 63enjoy** [comment]
如果不使用hook，仅靠内存数据很难准确监听事件
