### ISSUE TITLE
我可以帮忙管理这个库

### ISSUE THREAD

**Issue by theflysong** [Lazuplis-Mei/pvzclass#45]
RT
如果大大看到的话
我有比较多的时间可以上github
可以帮忙管理这个库

**Comment by Lazuplis-Mei** [comment]
好的，我可以转让给你，你就不要一直pr了

**Comment by Lazuplis-Mei** [comment]
本来我可以转让给你，不过转让操作提示theflysong/pvzclass already exists，你可能需要删除你的仓库，我不知道这是否会造成一些不必要的麻烦，所以暂时就先这样吧

**Comment by theflysong** [comment]
github可以不转让给予别人仓库权限的
