### ISSUE TITLE
setmemsize函数有什么作用

### ISSUE THREAD

**Issue by theflysong** [Lazuplis-Mei/pvzclass#56]
我是否可以认为调用完该函数后 plant/zombie在内存中的大小会相应的产生变化

BTW, 目前是否可以修改plant/zombie的动画属性 比如给它们换头

**Comment by Lazuplis-Mei** [comment]
可能是，但你最好向代码的提交者确认
应该不能，但你最好试试，因为我不知道

**Comment by Violet-Nonbloosom** [comment]
> 我是否可以认为调用完该函数后 plant/zombie在内存中的大小会相应的产生变化
> 
> BTW, 目前是否可以修改plant/zombie的动画属性 比如给它们换头

你确实可以这么认为，因为 SetMemSize() 设计出来就是为了实现指针扩展的。

BTW，换头相关的东西我不是很懂，所以我还是先不改了。
