### ISSUE TITLE
So, What's Definition?

### ISSUE THREAD

**Issue by theflysong** [Lazuplis-Mei/pvzclass#60]
这是什么？怎么用？qaq

**Comment by Violet-Nonbloosom** [comment]
获取一类植物（或者僵尸）共有的常量。
比如，示例代码中利用 PlantDefinition 获取三叶草的冷却。
另外，你也可以利用 ZombieDefinition 获取僵尸在冒险模式中首次出场的关卡。

**Comment by Violet-Nonbloosom** [comment]
至于怎么用的问题呢，你可以直接看示例代码。
