### ISSUE TITLE
关于交流群组和事件重写

### ISSUE THREAD

**Issue by Moon-404** [Lazuplis-Mei/pvzclass#62]
一方面，想交流一些 pvzclass 的开发经验；

另一方面，针对事件监听，我想使用一个更稳定的方式（比如 hook，Minecraft Forge 似乎就是这么做的）来重写，希望能有一个和其它 pvzclass 开发者共同交流的平台。

**Comment by Violet-Nonbloosom** [comment]
标题的问题，据我所知，没有。

欢迎建立交流群组讨论 pvzclass 开发。

事件监听确实需要好好重做一下。

**Comment by theflysong** [comment]
事件监听最理想的方式的确是利用hook 这种方式更加稳定 而原先监听数据的方法也确实会产生错误
但利用hook意味着需要向PVZ程序中插入代码
和Minecraft不同, PVZ并不运行在虚拟机上 因此对其程序的修改难度比Forge高很多
如果有能力的话 最好的方法是把PVZ反编译为C++代码再修改

**Comment by Moon-404** [comment]
我希望能由这个仓库的所有者或者 pvzclass 的主要开发者创建一个开发交流群，我个人没什么影响力。

我这两天会尝试制作一个 hook 事件的例子，可以让大家先看看效果。

**Comment by Moon-404** [comment]
我已经创建了一个 pvzclass 开发交流 QQ 群：894818406，我只是先开个头，希望可以由一个更有影响力的人来担任群主。

另外，我已经完成了一个简单的示例代码，大致思路是使用 hook 将重要事件的参数保存到一个事件共用的内存段， pvzclass 则通过循环读取这段的内容将其转换为对象进行处理，详见：

https://github.com/Moon-404/pvzclass/commit/7ed3c8767f0bc05f218d8a9fd660547ff3827eea

由于这个操作是线程阻塞的，优点是不会漏触发事件，缺点是会降低游戏的运行效率。如果能让 pvz 来调用外部代码（例如 dll 中的代码）可能会好很多。

**Comment by Moon-404** [comment]
已经完成并且提交了 pull request

**Comment by Moon-404** [comment]
Merged
