### ISSUE TITLE
需要精简仓库中代码和更合适的教程

### ISSUE THREAD

**Issue by Moon-404** [Lazuplis-Mei/pvzclass#64]
我已经在重构事件部分的代码了，但是原本的事件实现我并没有删除。我觉得是时候将仓库中的代码审阅一遍并清除效果不好的代码，这样子使用者的思路也会更加清晰。我本来想做这件事的，一方面我觉得重构事件更重要，另一方面我并没有参与到之前的开发中，不确定删除某些代码对整个仓库的影响。所以我希望由更了解这个仓库的人将这件事提上日程。

另外，现在的README似乎有点不明所以，它并没有详细介绍pvzclass的使用方式以及文件结构，我认为README的重写也需要提上日程。

我已经创建了QQ开发交流群，如果能提供帮助欢迎加入：894818406

**Comment by Violet-Nonbloosom** [comment]
文件夹里有一份旧的 README，还保留了不少有效描述代码的内容。

我改写一下它吧。
