### ISSUE TITLE
新事件组件的问题&建议收集处

### ISSUE THREAD

**Issue by Moon-404** [Lazuplis-Mei/pvzclass#69]
折腾了几天，根据 pvzclass 中已有的常用函数，我使用断点的方式制作了 17 个事件。

第一批事件我打算先更新这么多，这些都是共性的事件，之后要更新就是针对一些特性了。

特性事件又多又杂更新麻烦，所以一方面需要大家对已有事件提出意见和建议，另一方面需要大家告诉我哪些特性事件是用的比较多的，我优先开发。

当然，如果有大佬愿意自己制作一些事件代码贡献上来是最好，也可以加入 pvzclass 开发群交流：894818406。

**Comment by Violet-Nonbloosom** [comment]
一个主意，或者是更多个：
把植物、僵尸、子弹三种物体的更新函数加入事件如何？
除了难以调整 PVZ 本体的更改，这仨事件能做到的事情还真不少。
要不试一试？

**Comment by Moon-404** [comment]
> 一个主意，或者是更多个： 把植物、僵尸、子弹三种物体的更新函数加入事件如何？ 除了难以调整 PVZ 本体的更改，这仨事件能做到的事情还真不少。 要不试一试？

我近期比较忙，月底会尝试制作一下。不过更新事件会不会触发得过于频繁了，可能会大幅影响性能？

**Comment by Violet-Nonbloosom** [comment]
> > 一个主意，或者是更多个： 把植物、僵尸、子弹三种物体的更新函数加入事件如何？ 除了难以调整 PVZ 本体的更改，这仨事件能做到的事情还真不少。 要不试一试？
> 
> 我近期比较忙，月底会尝试制作一下。不过更新事件会不会触发得过于频繁了，可能会大幅影响性能？

那恐怕得退而求其次，只在遍历更新这三种对象的代码前头加一个“某类对象更新开始”的事件了。

虽然事件触发后续效果的用时被集中到了一起，但也减少了频繁恢复上下文的影响。

**Comment by Moon-404** [comment]
一个严重问题：事件组件与Execute不兼容，会导致阻塞。
排查了一天，问题定位到了：DebugActiveProcess时，CreateRemoteThread不会正常运行。
需要一些技术支持。
------
问题已解决，如果需要在事件的监听器中使用远程代码，请单独开一个线程处理。
