### ISSUE TITLE
Memory::Execute 导致崩溃

### ISSUE THREAD

**Issue by panic-0** [Lazuplis-Mei/pvzclass#84]
表现为 Access Violation 或 PVZ 程序无响应卡死。

2e15ec5 进行了修复，但使用 `SuspendThread` 可能导致主线程死锁。

**Comment by Violet-Nonbloosom** [comment]
我也没啥好的解决方案。

常规环境下问题不大，高速环境还是乖乖用 `Injector` 吧。

**Comment by Moon-404** [comment]
理论上讲 `SuspendThread` 的出错概率会更小一些，但无论是什么外在表现，可能还是得找到导致崩溃的具体原因才能解决这个问题，但是我没什么头绪。
